name: Update D-n Labels
on:
  schedule:
    - cron: '0 15 * * *' # 매일 밤 12시에 실행 (KST 기준)
jobs:
  d-day-labeler:
    runs-on: [ubuntu-latest]
    steps:
      - name: Update D-n Labels
        uses: naver/d-day-labeler@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          skipDraft: true # Draft PR을 건너뛰려면 true로 설정 (선택사항)